// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'icon-fenxiang': string;
  'icon-guangbo': string;
  'iconfont': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
