// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  des: string;
  icon: string;
  'icon-fenxiang': string;
  'icon-guangbo': string;
  iconfont: string;
  test__image: string;
  title: string;
}
declare let cssExports: CssExports;
export = cssExports;
